'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar_Estudiante_Reg", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Buscar_Estudiante_Reg(ByVal ced As String) As ServiceReference1.Estudiante_Reg
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar_Estudiante_Reg", ReplyAction:="*")>  _
        Function Buscar_Estudiante_RegAsync(ByVal ced As String) As System.Threading.Tasks.Task(Of ServiceReference1.Estudiante_Reg)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar_Profesor_Reg", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Buscar_Profesor_Reg(ByVal cod As String) As ServiceReference1.Profesor_Reg
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar_Profesor_Reg", ReplyAction:="*")>  _
        Function Buscar_Profesor_RegAsync(ByVal cod As String) As System.Threading.Tasks.Task(Of ServiceReference1.Profesor_Reg)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar_Facultad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Buscar_Facultad() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar_Facultad", ReplyAction:="*")>  _
        Function Buscar_FacultadAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar_Categoria", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Buscar_Categoria() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar_Categoria", ReplyAction:="*")>  _
        Function Buscar_CategoriaAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar_Profesor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Listar_Profesor() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar_Profesor", ReplyAction:="*")>  _
        Function Listar_ProfesorAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar_Estudiante", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Listar_Estudiante() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar_Estudiante", ReplyAction:="*")>  _
        Function Listar_EstudianteAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar_Profesor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Agregar_Profesor(ByVal v_codigo As String, ByVal v_cedula As String, ByVal v_nombre As String, ByVal v_apellido As String, ByVal v_direccion As String, ByVal v_celular As String, ByVal v_correo As String, ByVal v_facultad As String, ByVal v_categoria As String, ByVal v_salario As Decimal, ByVal v_status As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar_Profesor", ReplyAction:="*")>  _
        Function Agregar_ProfesorAsync(ByVal v_codigo As String, ByVal v_cedula As String, ByVal v_nombre As String, ByVal v_apellido As String, ByVal v_direccion As String, ByVal v_celular As String, ByVal v_correo As String, ByVal v_facultad As String, ByVal v_categoria As String, ByVal v_salario As Decimal, ByVal v_status As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Actualizar_Profesor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Actualizar_Profesor(ByVal v_nombre As String, ByVal v_apellido As String, ByVal v_direccion As String, ByVal v_celular As String, ByVal v_correo As String, ByVal v_facultad As String, ByVal v_categoria As String, ByVal v_salario As Decimal, ByVal v_status As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Actualizar_Profesor", ReplyAction:="*")>  _
        Function Actualizar_ProfesorAsync(ByVal v_nombre As String, ByVal v_apellido As String, ByVal v_direccion As String, ByVal v_celular As String, ByVal v_correo As String, ByVal v_facultad As String, ByVal v_categoria As String, ByVal v_salario As Decimal, ByVal v_status As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Estudiante_Reg
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private radioField As String
        
        Private cedulaField As String
        
        Private nombreField As String
        
        Private apellidoField As String
        
        Private direccionField As String
        
        Private celularField As String
        
        Private correoField As String
        
        Private facultadField As String
        
        Private carreraField As String
        
        Private indiceField As Decimal
        
        Private sexoField As String
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property radio() As String
            Get
                Return Me.radioField
            End Get
            Set
                Me.radioField = value
                Me.RaisePropertyChanged("radio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property cedula() As String
            Get
                Return Me.cedulaField
            End Get
            Set
                Me.cedulaField = value
                Me.RaisePropertyChanged("cedula")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
                Me.RaisePropertyChanged("apellido")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("direccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property celular() As String
            Get
                Return Me.celularField
            End Get
            Set
                Me.celularField = value
                Me.RaisePropertyChanged("celular")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
                Me.RaisePropertyChanged("correo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property facultad() As String
            Get
                Return Me.facultadField
            End Get
            Set
                Me.facultadField = value
                Me.RaisePropertyChanged("facultad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property carrera() As String
            Get
                Return Me.carreraField
            End Get
            Set
                Me.carreraField = value
                Me.RaisePropertyChanged("carrera")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property indice() As Decimal
            Get
                Return Me.indiceField
            End Get
            Set
                Me.indiceField = value
                Me.RaisePropertyChanged("indice")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
                Me.RaisePropertyChanged("sexo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Profesor_Reg
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private radioField As String
        
        Private codigoField As String
        
        Private cedulaField As String
        
        Private nombreField As String
        
        Private apellidoField As String
        
        Private direccionField As String
        
        Private celularField As String
        
        Private correoField As String
        
        Private facultadField As String
        
        Private categoriaField As String
        
        Private salarioField As Decimal
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property radio() As String
            Get
                Return Me.radioField
            End Get
            Set
                Me.radioField = value
                Me.RaisePropertyChanged("radio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property cedula() As String
            Get
                Return Me.cedulaField
            End Get
            Set
                Me.cedulaField = value
                Me.RaisePropertyChanged("cedula")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
                Me.RaisePropertyChanged("apellido")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("direccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property celular() As String
            Get
                Return Me.celularField
            End Get
            Set
                Me.celularField = value
                Me.RaisePropertyChanged("celular")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
                Me.RaisePropertyChanged("correo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property facultad() As String
            Get
                Return Me.facultadField
            End Get
            Set
                Me.facultadField = value
                Me.RaisePropertyChanged("facultad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property categoria() As String
            Get
                Return Me.categoriaField
            End Get
            Set
                Me.categoriaField = value
                Me.RaisePropertyChanged("categoria")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property salario() As Decimal
            Get
                Return Me.salarioField
            End Get
            Set
                Me.salarioField = value
                Me.RaisePropertyChanged("salario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Buscar_Estudiante_Reg(ByVal ced As String) As ServiceReference1.Estudiante_Reg Implements ServiceReference1.WebService1Soap.Buscar_Estudiante_Reg
            Return MyBase.Channel.Buscar_Estudiante_Reg(ced)
        End Function
        
        Public Function Buscar_Estudiante_RegAsync(ByVal ced As String) As System.Threading.Tasks.Task(Of ServiceReference1.Estudiante_Reg) Implements ServiceReference1.WebService1Soap.Buscar_Estudiante_RegAsync
            Return MyBase.Channel.Buscar_Estudiante_RegAsync(ced)
        End Function
        
        Public Function Buscar_Profesor_Reg(ByVal cod As String) As ServiceReference1.Profesor_Reg Implements ServiceReference1.WebService1Soap.Buscar_Profesor_Reg
            Return MyBase.Channel.Buscar_Profesor_Reg(cod)
        End Function
        
        Public Function Buscar_Profesor_RegAsync(ByVal cod As String) As System.Threading.Tasks.Task(Of ServiceReference1.Profesor_Reg) Implements ServiceReference1.WebService1Soap.Buscar_Profesor_RegAsync
            Return MyBase.Channel.Buscar_Profesor_RegAsync(cod)
        End Function
        
        Public Function Buscar_Facultad() As System.Data.DataTable Implements ServiceReference1.WebService1Soap.Buscar_Facultad
            Return MyBase.Channel.Buscar_Facultad
        End Function
        
        Public Function Buscar_FacultadAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceReference1.WebService1Soap.Buscar_FacultadAsync
            Return MyBase.Channel.Buscar_FacultadAsync
        End Function
        
        Public Function Buscar_Categoria() As System.Data.DataTable Implements ServiceReference1.WebService1Soap.Buscar_Categoria
            Return MyBase.Channel.Buscar_Categoria
        End Function
        
        Public Function Buscar_CategoriaAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceReference1.WebService1Soap.Buscar_CategoriaAsync
            Return MyBase.Channel.Buscar_CategoriaAsync
        End Function
        
        Public Function Listar_Profesor() As System.Data.DataSet Implements ServiceReference1.WebService1Soap.Listar_Profesor
            Return MyBase.Channel.Listar_Profesor
        End Function
        
        Public Function Listar_ProfesorAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService1Soap.Listar_ProfesorAsync
            Return MyBase.Channel.Listar_ProfesorAsync
        End Function
        
        Public Function Listar_Estudiante() As System.Data.DataSet Implements ServiceReference1.WebService1Soap.Listar_Estudiante
            Return MyBase.Channel.Listar_Estudiante
        End Function
        
        Public Function Listar_EstudianteAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService1Soap.Listar_EstudianteAsync
            Return MyBase.Channel.Listar_EstudianteAsync
        End Function
        
        Public Function Agregar_Profesor(ByVal v_codigo As String, ByVal v_cedula As String, ByVal v_nombre As String, ByVal v_apellido As String, ByVal v_direccion As String, ByVal v_celular As String, ByVal v_correo As String, ByVal v_facultad As String, ByVal v_categoria As String, ByVal v_salario As Decimal, ByVal v_status As String) As Boolean Implements ServiceReference1.WebService1Soap.Agregar_Profesor
            Return MyBase.Channel.Agregar_Profesor(v_codigo, v_cedula, v_nombre, v_apellido, v_direccion, v_celular, v_correo, v_facultad, v_categoria, v_salario, v_status)
        End Function
        
        Public Function Agregar_ProfesorAsync(ByVal v_codigo As String, ByVal v_cedula As String, ByVal v_nombre As String, ByVal v_apellido As String, ByVal v_direccion As String, ByVal v_celular As String, ByVal v_correo As String, ByVal v_facultad As String, ByVal v_categoria As String, ByVal v_salario As Decimal, ByVal v_status As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.WebService1Soap.Agregar_ProfesorAsync
            Return MyBase.Channel.Agregar_ProfesorAsync(v_codigo, v_cedula, v_nombre, v_apellido, v_direccion, v_celular, v_correo, v_facultad, v_categoria, v_salario, v_status)
        End Function
        
        Public Function Actualizar_Profesor(ByVal v_nombre As String, ByVal v_apellido As String, ByVal v_direccion As String, ByVal v_celular As String, ByVal v_correo As String, ByVal v_facultad As String, ByVal v_categoria As String, ByVal v_salario As Decimal, ByVal v_status As String) As Boolean Implements ServiceReference1.WebService1Soap.Actualizar_Profesor
            Return MyBase.Channel.Actualizar_Profesor(v_nombre, v_apellido, v_direccion, v_celular, v_correo, v_facultad, v_categoria, v_salario, v_status)
        End Function
        
        Public Function Actualizar_ProfesorAsync(ByVal v_nombre As String, ByVal v_apellido As String, ByVal v_direccion As String, ByVal v_celular As String, ByVal v_correo As String, ByVal v_facultad As String, ByVal v_categoria As String, ByVal v_salario As Decimal, ByVal v_status As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.WebService1Soap.Actualizar_ProfesorAsync
            Return MyBase.Channel.Actualizar_ProfesorAsync(v_nombre, v_apellido, v_direccion, v_celular, v_correo, v_facultad, v_categoria, v_salario, v_status)
        End Function
    End Class
End Namespace
